version: '3.7'
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/src
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://psu:psu@localhost:5432/todos"

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: psu
      POSTGRES_USER: psu
      POSTGRES_DB: todos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
