version: '3.7'
services:
  app:
    build:
      context: .
      target: runner
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/src
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://psu:psu@db:5432/todos"

  test:
    build:
      context: .
      target: test
    command: ["pytest", "/tests"]
    volumes:
      - .:/src
    depends_on:
      - db

  mypy:
    build:
      context: .
      target: test
    command: ["mypy", "/src"]
    volumes:
      - .:/src

  black:
    build:
      context: .
      target: test
    command: ["black", "/src"]
    volumes:
      - .:/src

  flake8:
    build:
      context: .
      target: test
    command: ["flake8", "/src"]
    volumes:
      - .:/src

  isort:
    build:
      context: .
      target: test
    command: ["isort", "/src"]
    volumes:
      - .:/src

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: psu
      POSTGRES_USER: psu
      POSTGRES_DB: todos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
